### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-intermedia-amandapalma#1]
Muy buen trabajo @amandapalma!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 312 / 347
- [x] HTML > LINK: Debemos tener dos ficheros de estilos importados con un `link`.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: Los enlaces tienen que tener el atributo `title`.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos. `.header .wrapper { align-items: center }`
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by amandapalma** [comment]
Hola @migueldelmazo !
Muchas gracias por las mejoras. He revisado punto por punto y creo que ya estarían corregidas todas, excepto la primera. 
No entiendo muy bien a qué te refieres ahí. En la línea 12 y 13 del archivo html hay dos links hacia las hojas de estilo 'style.css' y 'reset.css'. Y los archivos se encuentran en la carpeta 'styles'. ¿Qué es lo que tendría que hacer entonces para corregir ese punto?
Muchas gracias!!!! ;)

**Comment by migueldelmazo** [comment]
Hola @amandapalma,

> No entiendo muy bien a qué te refieres ahí. En la línea 12 y 13 del archivo html hay dos links hacia las hojas de estilo 'style.css' y 'reset.css'. Y los archivos se encuentran en la carpeta 'styles'. ¿Qué es lo que tendría que hacer entonces para corregir ese punto?

Esto es fallo mío, no te preocupes.

Muy buen curro y sigue así!!!

**Comment by amandapalma** [comment]
Ok, @migueldelmazo, entonces doy por corregido mi ejercicio. He marcado la corrección de la primera línea como realizada también.
Gracias por las correcciones!
